### ISSUE TITLE
Default Placeholder Assets

### ISSUE THREAD

**Issue by mmMarzban** [YoYoGames/GameMaker-Feature-Requests#1198]
### Is your feature request related to a problem?

Many times you need to test some very quick prototype and you just need some sprite(s) to start the job! If GameMaker could add some default placeholders for that it was great. Godot adds it's Icon in every new project and thousands of tutorials are created just based on this very single sprite!

### Describe the solution you'd like

Just add one (or a couple of sprites) to every newly-created project , which can be deleted (if the user wishes so). Like Godot you can use GM's icon or a symbolic character for GM.(for example the face of Matharoo would be a good idea - just kidding!)

### Describe alternatives you've considered

Alternative? Are you serious?

### Additional context

Additional Context? Are you serious?

**Comment by gnysek** [comment]
This sounds exactly like https://github.com/YoYoGames/GameMaker-Feature-Requests/issues/1097 .

**Comment by mmMarzban** [comment]
You misunderstood the point Gnysek. That's not it.

**Comment by gnysek** [comment]
Adding sprite requires clicking Alt+S, come on!

**Comment by mmMarzban** [comment]
And adding lights need a surface and a bm_subtract and an ALT+S for a halo sprite. Come on!

**Comment by Alphish** [comment]
Actually, I'd say it's more of a project template thing, which already exists. But I wouldn't mind having placeholders included in the default template, especially since they can streamline the tinker projects and GM tutorials quite a bit (the tutorial can just say "now do thing X with the placeholder sprite" instead of having the user go through a small hassle of adding a new sprite and importing/editing its visuals, especially if they're unfamiliar in the first place).

Is it the top priority thing I'd like YYG to work on? Not really, but I wouldn't mind it added, either. ^^'

**Comment by mmMarzban** [comment]
Sure it is not a top priority. However GM does need some quality of life additions.

**Comment by gnysek** [comment]
Actually for em it wouldn't be QoL update and would rather annoy me, to have resources I don't want by default.
However, creating templates which can be later used as base for new project (for example from prefabs), is a nice idea.

**Comment by efeberku** [comment]
1-) Create a new project.
2-) Add sprites or default placeholders or whatever you like.
3-) Export it.
4-) Import that yyz instead of opening a new project.

**Comment by jackerley** [comment]
We would recommend using your own project template if you wish to start a project with sprites already in it.
