### ISSUE TITLE
add a way to store and set the state of the random number generator seed

### ISSUE THREAD

**Issue by attic-stuff** [YoYoGames/GameMaker-Feature-Requests#1206]
### Is your feature request related to a problem?

yes! currently if you pull this slick move:
```gml
/*fun event*/
randomise();
savedseed = random_get_seed();
irandom(5);
irandom(5);
```
you will get two random numbers. if you serialize that seed, and then do this when the game launches again:
```gml
/*fun event*/
random_set_seed(savedseed);
irandom(5);
irandom(5);
```
you will get the same two random numbers as when we first generated this seed! it would be nice to be able to save the state of the random number generator so that you can sort of pick up where you left off when it comes to random calls.

### Describe the solution you'd like

i would like to see two (2) functions added to gamemaker for this: a random_get_state() and a random_set_state(); the former would return the state of the rng given the current seed and the latter would be able to "catch up" the state of the current seed to whatever random_get_state() returns.

### Describe alternatives you've considered

friends i have had to make my own wrapper for every random call to log the type of call, then run through every call at game relaunch to catch the state up.

### Additional context

there is no additional context, that's the end folks.

**Comment by Alphish** [comment]
If you need a reliable Pseudo-Random Number Generator, I'd suggest a custom solution, like e.g. [GMXorWow](https://marketplace.gamemaker.io/assets/9674/gmxorwow) (with repository available [here](https://github.com/dicksonlaw583/GMXorWow)).

I recommend this, because the built-in PRNG might be inconsistent across platforms, making it a poor candidate to produce consistent random sequences in the first place. Quoting from the [manual page on random_set_seed](https://manual.yoyogames.com/#t=GameMaker_Language%2FGML_Reference%2FMaths_And_Numbers%2FNumber_Functions%2Frandom_set_seed.htm):
> While this seed will give consistent results on each target platform, results may vary between platforms due to the different way each target works.

Plus, I imagine platform-specific implementations use some kind of built-in RNG available for given platforms, and I'm not sure if all of these platforms make their RNG exact state available.

**Comment by DragoniteSpam** [comment]
What about something like `random_state_push()` and `random_state_pop()`? Would be a more generally useful solution than just saving and loading a single RNG seed.

**Comment by jackerley** [comment]
We're not planning on extending beyond random_get_seed() and random_set_seed()
