### ISSUE TITLE
asset_get_index doesn't return built-in functions

### ISSUE THREAD

**Issue by Psycho-Male** [YoYoGames/GameMaker-Feature-Requests#1323]
### Is your feature request related to a problem?

I can get names of the built-in functions using script_get_name but I can't do the reverse. In my case, this usage is intended for an external tool(without dll) and custom console.

### Describe the solution you'd like

 I'd like to get built-in functions using asset_get_index.

### Describe alternatives you've considered

Writing a script that includes each built-in function names.

**Comment by jackerley** [comment]
built in functions aren't assets

**Comment by tinkerer-red** [comment]
Think this should be reopened and renamed. The issue at hand isn't specifically the differences between assets and built in functions.
The actual request would be asking for some way to reference a function index from a function name string, which we have no way of doing except for `asset_get_index` which conversely doesnt work for built in functions.

Personally due to the fact `script_get_name()` exists, but to reference a script's index you need to use `asset_get_index`, why not just include a `script_get_index( name )` would help standardize the differences between function's gets/sets which has many differences.

**Comment by Psycho-Male** [comment]
Supports answer was really lazy and it annoyed so I left it alone, thanks for bringing this up and putting it in better words.

 The fact that asset_get_index works with functions makes the argument "built in functions aren't assets" pretty much invalid. Or are you saying we are creating new assets whenever we declare function/method? I doubt that. Yoyo even added support for built-in functions into `script_execute` and `method_call`, but this limitation is really bummer.
 
 That aside, it should've been obvious that, us, considering them asset or not, is irrelevant to my request.
