### ISSUE TITLE
String Literal Struct Accessor to Hash Optimization

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Feature-Requests#1465]
### Is your feature request related to a problem?

Would be nice if string literals would be converted into hash look ups when using `struct_get`,  `struct_exists`, or the `[$ ""]` operator  at compile time.

evidence of this not happening:
YYC:
![image](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/48543299/b76a7113-e132-4ec5-be85-fbd2d08a3fb9)
VM:
![image](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/48543299/738c7c8c-c8c3-4272-86ec-64c32e37982d)

### Describe the solution you'd like

when a string literal is given to a struct accessor it should be converted into a hash look up with a real literal at compile time.

### Describe alternatives you've considered

adding a build script to my projects to optimize.

Using forceinline functions with statics which will cache the hash the first time then always returns that. But this does not actually work.

**Comment by rwkay** [comment]
Fixed in 2024.2 - optimisations have been added
* `variable_struct_get` is now optimised if the second parameter is a constant string e.g if `variable_struct_get( a, "hello" )` it now gets optimised to `a.hello`
• `variable_struct_set` is now optimised if the second parameter is a constant string e.g. `variable_struct_set( a, "hello", 20)` is optimised to be `a.hello = 20`

NOTE: `a[$ "hello" ] = 20` is already turned into `variable_struct_set( a, "hello", 20)` as part of the accessor framework similarly any reference to the value `a[$ "hello" ]` is turned into `variable_struct_get( a, "hello" )`. So this accomplishes the desired result.

My test code for this is

```
var a = { Hello : 20 };

var b = a[$ "Hello" ];
a[$ "foo" ] = "foo";
show_debug_message( $"b = {b},a = {a}" );
```

**Comment by gnysek** [comment]
@rwkay if it's optimised this way, then it would break existing functionality as `variable_struct_get` can return `undefined` if property doesn't exist, while `a.hello` would crash game in that case.
Should it be that `variable_struct_get( a, "hello" )` is optimised to `a.hello ?? undefined` ??

**Comment by tinkerer-red** [comment]
..or `struct_set_from_hash(a, <"hello" hash litteral>)` which does return undefined

**Comment by rwkay** [comment]
OK this is now fixed for the case where `hello` does not exist on `a` it now returns undefined

`variable_struct_get` is now optimised if the second parameter is a constant string e.g if variable_struct_get( a, "hello" ) it now gets optimised to `struct_get_from_hash( a, #"hello" )` where `#"hello"` is the hash for the variable named `hello`

**Comment by tinkerer-red** [comment]
Does that mean we can now use hash literals? like for instance if I want to pass `#"hello"` into a function such as `trigger_event(#"onCollide")`

**Comment by rwkay** [comment]
No it is just a notation I was using to describe what is happening it is not GML syntax
