### ISSUE TITLE
`string_pos_ext` support for negative positioning

### ISSUE THREAD

**Issue by tinkerer-red** [YoYoGames/GameMaker-Feature-Requests#1564]
### Is your feature request related to a problem?

Allow for `string_pos_ext` to support negative positioning to implicate searching backwards from a position.

### Describe the solution you'd like

So for instance in the given string `"hello world"` if one wanted to find the last `l` in the string one could make use of `string_pos_ext("l", "hello world", -1)`

### Describe alternatives you've considered

just making my own function to support such things.

**Comment by shdwcat** [comment]
Maybe it would be clearer to have `string_last_pos` and `string_last_pos_ext`? The negative parameter is neat, but in other languages like C# you usually just get separate functions for them.

**Comment by tinkerer-red** [comment]
Was going off the fact that a very few other functions in gml also allow for negative numbers, though usually to refer to a negative length such as `string_foreach`. But yeah it does seem more inline to have additional named functions for gml.

**Comment by katsaii** [comment]
I would rather have a `string_last_pos_ext` or something similar, just because to me passing in a negative offset would just mean the function would begin searching at the last character of the string. Typically this would be a single character long and not very useful.

If you want the search direction to change based off of the sign of the offset parameter, I personally think that's very confusing and would prefer a separate function.

**Comment by Alphish** [comment]
Um, everyone...?
https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FStrings%2Fstring_last_pos.htm
https://manual.gamemaker.io/monthly/en/#t=GameMaker_Language%2FGML_Reference%2FStrings%2Fstring_last_pos_ext.htm

**Comment by tinkerer-red** [comment]
oh... whelp time to close
