### ISSUE TITLE
Please bring back this option: "Treat uninitialized variables as value 0"

### ISSUE THREAD

**Issue by WinMithul** [YoYoGames/GameMaker-Feature-Requests#1568]
### Is your feature request related to a problem?

I am always frustrated with this frequent game error: <variable_name> is not set before reading it. 
It gives me a headache when I keep initializing all variables if there are thousands.
And if I did initialize some variables, my whole game would be ruined with glitches.

### Describe the solution you'd like

If the option is added, users need not initialize all the variables. That would save a lot of time and work while testing the game. 

### Additional context

This feature existed in the old days, before the GameMaker Studio era(mostly GM6/GM7/GM8.x). However, this useful feature was killed when GameMaker: Studio was launched and it didn't come back at all...

_No response_

**Comment by BackYard321** [comment]
TBQH I kind of would like some version of this with `undefined`, as functions like `array_pop()` or `variable_instance_get()` will return `undefined` if there's no entry/variable associated with them, rather than just erroring out. 

It WOULD be nice to have the equivalent of `gml_release_mode()` for enabling/disabling this, although obviously I can imagine this is a whole can of worms that could create a huge number of debugging issues.

**Comment by Hyomoto** [comment]
"And if I did initialize some variables, my whole game would be ruined with glitches." And yet, the solution you want is a built-in feature to make it easier for glitches to happen? This is, at best, a highly contentious topic.

Still, this feature exists. GM does allow you to use undeclared variables and will even return undefined (which could then be used with ?? to get 0). This is the [$ "" ] format. One could argue this feature already exists in a safe way if its needed, and this preferred since you must deliberately choose to do it, thus accepting any risk that comes with it.

**Comment by mistletoe** [comment]
I'm really just wondering what you'd really want to leave like that for long enough to cause a crash, honestly. If you need a variable to stay undefined for a long time, simply initialize it with _undefined_ and check against that; it's not a number.

A bit more back-and-forth context on this:

https://forum.gamemaker.io/index.php?threads/difference-between-undefined-and-variable-not-set.81853/

**Comment by jackerley** [comment]
We're not planning on having this feature.
