### ISSUE TITLE
Ticket: #181488 - Changing the room size from the top

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Feature-Requests#983]
Ticket: [Ticket #181488]

*Description:* When you type in the room size you want, instead of increasing/decreasing the size of the room from the bottom, the room in change size from the top.

*Benefit:* I made a big room, and to shrink it, I have to move every tile layer up to where I want the room size to be, then I lower the room size. If I lower the room size before moving the tiles, the tiles all get destroyed because it changed size from the bottom.

**Comment by glebtsereteli** [comment]
To expand on this, instead of just having an option to resize from the top, it'd be great to have a little menu for picking a "resize anchor point". Just like the one we have in the Sprite Editor when resizing a sprite. 
![image](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/50461722/ce37931c-01b9-41b1-afa0-8689868a4f86)

**Comment by KeeVeeGames** [comment]
Duplicate #1052

**Comment by Alphish** [comment]
@rwkay A duplicate.

**Comment by rwkay** [comment]
duplicate issue - closing this one
